server:
  port: 7001

# Eureka配置
eureka:
  instance:
    # Eureka服务端的实例名字
    #hostname: 127.0.0.1
    hostname: eureka7001.com #Eureka服务端的实例名字
  client:
    # 表示是否向 Eureka 注册中心注册自己(这个模块本身是服务器,所以不需要)，默认为true
    register-with-eureka: false
    # fetch-registry如果为false,则表示自己为注册中心,客户端为 ture，默认为true
    fetch-registry: false

    # Eureka监控页面~   yml中可以通过${}进行上下配置数据的引用，详见博客springboot-yaml
    service-url:
      #重写Eureka的默认端口以及访问路径 --->http://localhost:7001/eureka/
      # 单机： defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群（关联）：7001关联7002、7003
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/